CREATE TABLE `medrecord`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `mail` VARCHAR(255) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

LOCK TABLES 'medrecord'.'user' WRITE;
/*!40000 ALTER TABLE 'medrecord'.'user' DISABLE KEYS */;
INSERT INTO 'medrecord'.'user' VALUES (1,'USER1','PASSWORD1','MAIL1','PATIENT'),(2,'USER2','PASSWORD2','MAIL2','DOCTOR'),(3,'USER3','PASSWORD3','MAIL3','ADMIN');
/*!40000 ALTER TABLE 'medrecord'.'user' ENABLE KEYS */;
UNLOCK TABLES;